server:
  error:
    include-stacktrace: ON_PARAM #?trace=true

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/animes?useSSL=false&createDatabaseIfNotExists=true&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
